#########################################################################
# Title:         Shitbox: Shell Role                                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/shaboigan/Shitbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Import 'misc' subtask
  ansible.builtin.include_tasks: "subtasks/misc.yml"

- name: Import 'z' subtask
  ansible.builtin.include_tasks: "subtasks/z.yml"
  when: (not 'preinstall' in ansible_run_tags)

- name: Import '{{ shell_type }}' subtask
  ansible.builtin.include_tasks: "subtasks/shell/{{ shell_type }}.yml"
