#########################################################################
# Title:         Restore: Set '/opt' Ownership and Permissions Task     #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/shaboigan/Shitbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set '/opt' ownership recursively
  ansible.builtin.shell: "chown -R {{ user.name }}:{{ user.name }} /opt"

- name: Set '/opt' permissions recursively
  ansible.builtin.shell: "chmod -R ugo+X /opt"
