##########################################################################
# Title:         Shitbox: Plex DB | Default Variables                    #
# Author(s):     salty                                                   #
# URL:           https://github.com/shaboigan/Shitbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
plex_db_files:
  - "com.plexapp.plugins.library.db"
  - "com.plexapp.plugins.library.blobs.db"
