##########################################################################
# Title:         Shitbox: Backup | Default Variables                     #
# Author(s):     salty                                                   #
# URL:           https://github.com/shaboigan/Shitbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
backup2_ignore_containers: []
backup2_user_defined_files: []
backup2_async_batch_size: 99

# Options can be found at https://rclone.org/docs/#bwlimit-bandwidth-spec
backup2_rclone_upload_speed_limit: "off"
