#########################################################################
# Title:         Shitbox: Readarr Role                                  #
# Author(s):     salty                                                  #
# URL:           https://github.com/shaboigan/Shitbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Readarr roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    readarr_name: "{{ role }}"
  with_items: "{{ readarr_instances }}"
  loop_control:
    loop_var: role
