#########################################################################
# Title:            Shitbox: qbittorrent                             #
# Author(s):        salty                                               #
# URL:              https://github.com/shaboigan/Shitbox                 #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

qbittorrent_instances: ["qbittorrent"]

################################
# Paths
################################

qbittorrent_paths_folder: "{{ qbittorrent_name }}"
qbittorrent_paths_location: "{{ server_appdata_path }}/{{ qbittorrent_paths_folder }}"
qbittorrent_paths_downloads_location: "{{ downloads_torrents_path }}/{{ qbittorrent_paths_folder }}"
qbittorrent_paths_conf: "{{ qbittorrent_paths_location }}/qBittorrent/config/qBittorrent.conf"
qbittorrent_paths_folders_list:
  - "{{ qbittorrent_paths_location }}"
  - "{{ qbittorrent_paths_location }}/openvpn"
  - "{{ qbittorrent_paths_downloads_location }}"
  - "{{ qbittorrent_paths_downloads_location }}/completed"
  - "{{ qbittorrent_paths_downloads_location }}/incoming"
  - "{{ qbittorrent_paths_downloads_location }}/watched"
  - "{{ qbittorrent_paths_downloads_location }}/torrents"

################################
# Web
################################

qbittorrent_web_subdomain: "{{ qbittorrent_name }}"
qbittorrent_web_domain: "{{ user.domain }}"
qbittorrent_web_port: "8090"
qbittorrent_web_url: "{{ 'https://' + lookup('vars', qbittorrent_name + '_web_subdomain', default=qbittorrent_web_subdomain)
                            + '.' + lookup('vars', qbittorrent_name + '_web_domain', default=qbittorrent_web_domain) }}"

################################
# DNS
################################

qbittorrent_dns_record: "{{ lookup('vars', qbittorrent_name + '_web_subdomain', default=qbittorrent_web_subdomain) }}"
qbittorrent_dns_zone: "{{ lookup('vars', qbittorrent_name + '_web_domain', default=qbittorrent_web_domain) }}"
qbittorrent_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

qbittorrent_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
qbittorrent_traefik_middleware_default: "{{ traefik_default_middleware + ',' + qbittorrent_traefik_sso_middleware
                                            if (qbittorrent_traefik_sso_middleware | length > 0)
                                            else traefik_default_middleware }}"
qbittorrent_traefik_middleware_custom: ""
qbittorrent_traefik_middleware: "{{ qbittorrent_traefik_middleware_default + ','
                                       + qbittorrent_traefik_middleware_custom
                                    if (not qbittorrent_traefik_middleware_custom.startswith(',') and qbittorrent_traefik_middleware_custom | length > 0)
                                    else qbittorrent_traefik_middleware_default
                                       + qbittorrent_traefik_middleware_custom }}"
qbittorrent_traefik_certresolver: "{{ traefik_default_certresolver }}"
qbittorrent_traefik_enabled: true
qbittorrent_traefik_api_enabled: true
qbittorrent_traefik_api_endpoint: "`/api`,`/command`,`/query`,`/login`,`/sync`"

################################
# Docker
################################

# Container
qbittorrent_docker_container: "{{ qbittorrent_name }}"

# Image
qbittorrent_docker_image_pull: true
qbittorrent_docker_image_repo: "binhex/arch-qbittorrentvpn"
qbittorrent_docker_image_tag: "latest"
qbittorrent_docker_image: "{{ lookup('vars', qbittorrent_name + '_docker_image_repo', default=qbittorrent_docker_image_repo)
                                 + ':' + lookup('vars', qbittorrent_name + '_docker_image_tag', default=qbittorrent_docker_image_tag) }}"

# Ports
qbittorrent_docker_port: "27633"
qbittorrent_web_port_lookup: "{{ lookup('vars', qbittorrent_name + '_web_port', default=qbittorrent_web_port) }}"

qbittorrent_docker_ports_defaults:
  - "{{ qbittorrent_docker_port }}:{{ qbittorrent_docker_port }}"
qbittorrent_docker_ports_custom: []
qbittorrent_docker_ports: "{{ lookup('vars', qbittorrent_name + '_docker_ports_defaults', default=qbittorrent_docker_ports_defaults)
                                 + lookup('vars', qbittorrent_name + '_docker_ports_custom', default=qbittorrent_docker_ports_custom) }}"

################################
# Settings
################################

qbittorrent_log_level_daemon: info
qbittorrent_log_level_web: info
qbittorrent_name_servers: "84.200.69.80,1.1.1.1,84.200.70.40,1.0.0.1"
qbittorrent_lan_network: "172.19.0.0/16"

# Envs
qbittorrent_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  UMASK_SET: "002"
  VPN_ENABLED: "yes"
  VPN_PROV: "airvpn"
  STRICT_PORT_FORWARD: "yes"
  ENABLE_PRIVOXY: "no"
  LAN_NETWORK: "{{ qbittorrent_lan_network }}"
  NAME_SERVERS: "{{ qbittorrent_name_servers }}"

qbittorrent_docker_envs_custom: {}
qbittorrent_docker_envs: "{{ lookup('vars', qbittorrent_name + '_docker_envs_default', default=qbittorrent_docker_envs_default)
                                | combine(lookup('vars', qbittorrent_name + '_docker_envs_custom', default=qbittorrent_docker_envs_custom)) }}"

# Commands
qbittorrent_docker_commands_default: []
qbittorrent_docker_commands_custom: []
qbittorrent_docker_commands: "{{ lookup('vars', qbittorrent_name + '_docker_commands_default', default=qbittorrent_docker_commands_default)
                                    + lookup('vars', qbittorrent_name + '_docker_docker_commands_custom', default=qbittorrent_docker_commands_custom) }}"

# Volumes
qbittorrent_docker_volumes_default:
  - "{{ qbittorrent_paths_location }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
qbittorrent_docker_volumes_custom: []
qbittorrent_docker_volumes: "{{ lookup('vars', qbittorrent_name + '_docker_volumes_default', default=qbittorrent_docker_volumes_default)
                                   + lookup('vars', qbittorrent_name + '_docker_volumes_custom', default=qbittorrent_docker_volumes_custom) }}"

# Devices
qbittorrent_docker_devices_default: []
qbittorrent_docker_devices_custom: []
qbittorrent_docker_devices: "{{ lookup('vars', qbittorrent_name + '_docker_devices_default', default=qbittorrent_docker_devices_default)
                                   + lookup('vars', qbittorrent_name + '_docker_devices_custom', default=qbittorrent_docker_devices_custom) }}"

# Hosts
qbittorrent_docker_hosts_default: []
qbittorrent_docker_hosts_custom: []
qbittorrent_docker_hosts: "{{ docker_hosts_common
                                 | combine(lookup('vars', qbittorrent_name + '_docker_hosts_default', default=qbittorrent_docker_hosts_default))
                                 | combine(lookup('vars', qbittorrent_name + '_docker_hosts_custom', default=qbittorrent_docker_hosts_custom)) }}"

# Labels
qbittorrent_docker_labels_default: {}
qbittorrent_docker_labels_custom: {}
qbittorrent_docker_labels: "{{ docker_labels_common
                                  | combine(lookup('vars', qbittorrent_name + '_docker_labels_default', default=qbittorrent_docker_labels_default))
                                  | combine(lookup('vars', qbittorrent_name + '_docker_labels_custom', default=qbittorrent_docker_labels_custom)) }}"

# Hostname
qbittorrent_docker_hostname: "{{ qbittorrent_name }}"

# Networks
qbittorrent_docker_networks_alias: "{{ qbittorrent_name }}"
qbittorrent_docker_networks_default: []
qbittorrent_docker_networks_custom: []
qbittorrent_docker_networks: "{{ docker_networks_common
                                    + lookup('vars', qbittorrent_name + '_docker_networks_default', default=qbittorrent_docker_networks_default)
                                    + lookup('vars', qbittorrent_name + '_docker_networks_custom', default=qbittorrent_docker_networks_custom) }}"

# Capabilities
qbittorrent_docker_capabilities_default:
  - NET_ADMIN
qbittorrent_docker_capabilities_custom: []
qbittorrent_docker_capabilities: "{{ qbittorrent_docker_capabilities_default
                                        + qbittorrent_docker_capabilities_custom }}"

# Security Opts
qbittorrent_docker_security_opts_default: []
qbittorrent_docker_security_opts_custom: []
qbittorrent_docker_security_opts: "{{ lookup('vars', qbittorrent_name + '_docker_security_opts_default', default=qbittorrent_docker_security_opts_default)
                                         + lookup('vars', qbittorrent_name + '_docker_security_opts_custom', default=qbittorrent_docker_security_opts_custom) }}"
# Sysctls
qbittorrent_docker_sysctls:
  net.ipv4.conf.all.src_valid_mark: "1"

# Restart Policy
qbittorrent_docker_restart_policy: unless-stopped

# Stop Timeout
qbittorrent_docker_stop_timeout: 900

# State
qbittorrent_docker_state: started

# Privileged
qbittorrent_docker_privileged: "yes"
