#########################################################################
# Title:         Shitbox: Shell | Misc                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/shaboigan/Shitbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Misc | Install argcomplete
  ansible.builtin.shell: "pip install {{ shell_misc_argcomplete_pip_package }}"
  ignore_errors: true

# For Ansible command line utilities
- name: Misc | Activate argcomplete
  ansible.builtin.shell: "{{ shell_misc_argcomplete_command }}"
  ignore_errors: true
