#########################################################################
# Title:         Shitbox: Pre-Tasks                                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/shaboigan/Shitbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT Tasks
  ansible.builtin.import_tasks: "subtasks/apt.yml"

- name: Git Tasks
  ansible.builtin.import_tasks: "subtasks/git.yml"

- name: Variables Tasks
  ansible.builtin.include_tasks: "subtasks/variables.yml"
  when: (playbook_dir != "/srv/git/shitbox" and not continuous_integration) or (playbook_dir != "/home/runner/work/Shitbox/Shitbox" and continuous_integration)
