#########################################################################
# Title:         Shitbox: Python                                        #
# Author(s):     salty                                                  #
# URL:           https://github.com/shaboigan/Shitbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check System pip"
  ansible.builtin.command: "cat /usr/local/bin/pip"
  register: system_pip

- name: "Fix System pip"
  block:
    - name: "Replace 'python3.8' with 'python3'"
      ansible.builtin.shell: "sed -i 's/python3.8/python3/g' /usr/local/bin/pip"

  when: system_pip.stdout_lines[0] == "#!/usr/bin/python3.8"

- name: "Check System pip3"
  ansible.builtin.command: "cat /usr/local/bin/pip3"
  register: system_pip3

- name: "Fix System pip3"
  block:
    - name: "Replace 'python3.8' with 'python3'"
      ansible.builtin.shell: "sed -i 's/python3.8/python3/g' /usr/local/bin/pip3"

  when: system_pip3.stdout_lines[0] == "#!/usr/bin/python3.8"
