#########################################################################
# Title:         Shitbox: qbittorrent | Pre-Install Tasks            #
# Author(s):     salty                                                  #
# URL:           https://github.com/shaboigan/Shitbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Pre-Install | Check if opvn config file exists
  stat:
    path: "{{ qbittorrent_paths_location }}/openvpn/config.ovpn"
  register: config_ovpn

- name: Pre-Install | Import 'openvpn config'
  shell: "curl -Lo /opt/qbittorrent/openvpn/config.ovpn '{{ vpn.config }}'"
  become: yes
  become_user: "{{ user.name }}"
  when: not config_ovpn.stat.exists

- name: Pre-Install | Settings | Update 'qBittorrent.conf' config settings
  community.general.ini_file:
    path: "{{ qbittorrent_paths_conf }}"
    section: BitTorrent
    option: Session\Port
    value: "{{ qbittorrent_docker_ports }}"
    no_extra_spaces: true
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  when: qbittorrent_paths_conf_stat.stat.exists