#########################################################################
# Title:         Shitbox: Cloudflare | Subdomains Task                  #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/shaboigan/Shitbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
## Add 'shitbox_type' subdomain
- name: "Cloudflare | Subdomains | Add '{{ shitbox_type }}' subdomain to '{{ fld.stdout }}'"
  ansible.builtin.import_tasks: "subdomains/add_subdomain.yml"

## Remove 'shitbox' subdomain for Mediabox/Feederbox setups.
- name: "Cloudflare | Subdomains | Remove 'shitbox' subdomain from '{{ fld.stdout }}'"
  ansible.builtin.import_tasks: "subdomains/remove_subdomain.yml"
  when: shitbox_type is regex('mediabox|feederbox')
